language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
# command to run tests
script: coverage run --source=. -m unittest discover
after_success: coveralls